### success (admin):
DELETE {{baseUrl}}/api/admin/time_detail?train_code=T999&indexes=2
Authorization: admin:admin

### success (admin): delete all
DELETE {{baseUrl}}/api/admin/time_details?train_code=T999
Authorization: admin:admin

### fail: no such time_detail
DELETE {{baseUrl}}/api/admin/time_detail/-1
Authorization: admin:admin

###
