### success 1
GET {{baseUrl}}/api/ticket/1
Authorization: CarlRabbit:123456

### success 2
GET {{baseUrl}}/api/ticket/2
Authorization: CarlRabbit:123456

### success 3 (admin)
GET {{baseUrl}}/api/admin/ticket/1
Authorization: admin:admin

### fail: other user's psg
GET {{baseUrl}}/api/ticket/3
Authorization: CarlRabbit:123456

###