### success (admin): Warning, delete cascade
DELETE {{baseUrl}}/api/admin/city?name=八原
Authorization: admin:admin

### add city (add in advence)
POST {{baseUrl}}/api/admin/city
Authorization: admin:admin
Content-Type: application/json

{
  "city_name": "八原",
  "province": "神都"
}

### add station 1 (add in advence)
POST {{baseUrl}}/api/admin/station
Authorization: admin:admin
Content-Type: application/json

{
  "station_name": "油屋",
  "station_code": "XYW",
  "city_id": 391
}

### add station 2 (add in advence)
POST {{baseUrl}}/api/admin/station
Authorization: admin:admin
Content-Type: application/json

{
  "station_name": "沼原",
  "station_code": "XZY",
  "city_id": 391
}

### add station 3 (add in advence)
POST {{baseUrl}}/api/admin/station
Authorization: admin:admin
Content-Type: application/json

{
  "station_name": "沼底",
  "station_code": "XZD",
  "city_id": 391
}

### add station 4
POST {{baseUrl}}/api/admin/station
Authorization: admin:admin
Content-Type: application/json

{
  "station_name": "浮春之乡",
  "station_code": "FCX",
  "city_id": 391
}

### check stations by city_name
GET {{baseUrl}}/api/station?city_name=八原

### add train detail 1
POST {{baseUrl}}/api/admin/time_detail
Authorization: admin:admin
Content-Type: application/json

{
  "train_code": "T999",
  "station_id": 5204,
  "station_index": 1,
  "arrive_time": "00:00:00",
  "leave_time": "00:00:00",
  "runtime": "00:00:00",
  "mileage": 15
}

### add train detail 2
POST {{baseUrl}}/api/admin/time_detail
Authorization: admin:admin
Content-Type: application/json

{
  "train_code": "T999",
  "station_id": 5205,
  "station_index": 2,
  "arrive_time": "01:00:00",
  "leave_time": "01:03:00",
  "runtime": "01:00:00",
  "mileage": 25
}

### add train detail 3
POST {{baseUrl}}/api/admin/time_detail
Authorization: admin:admin
Content-Type: application/json

{
  "train_code": "T999",
  "station_id": 5206,
  "station_index": 3,
  "arrive_time": "02:00:00",
  "leave_time": "02:03:00",
  "runtime": "02:00:00",
  "mileage": 35
}

### add train detail 4
POST {{baseUrl}}/api/admin/time_detail
Authorization: admin:admin
Content-Type: application/json

{
  "train_code": "T999",
  "station_id": 5207,
  "station_index": 4,
  "arrive_time": "03:00:00",
  "leave_time": "03:00:00",
  "runtime": "03:00:00",
  "mileage": 45
}

### fail: (train_code, station_indexal) ready exists
POST {{baseUrl}}/api/admin/time_detail
Authorization: admin:admin
Content-Type: application/json

{
  "train_code": "T999",
  "station_id": 5208,
  "station_index": 4,
  "arrive_time": "04:00:00",
  "leave_time": "04:00:00",
  "runtime": "04:00:00",
  "mileage": 55
}

### see as admin
GET {{baseUrl}}/api/admin/time_details?train_code=T999
Authorization: admin:admin

### see as user
GET {{baseUrl}}/api/routes/detail/T999


### motify time detail list ###

### delete station by index
DELETE {{baseUrl}}/api/admin/time_detail?train_code=T999&indexes=2,3
Authorization: admin:admin

### update index and time, ready for add 2 back
PUT {{baseUrl}}/api/admin/time_detail
Authorization: admin:admin
Content-Type: application/json

{
  "time_detail_id": 93601,
  "station_index": 3,
  "arrive_time": "04:00:00",
  "leave_time": "04:00:00"
}

### add 2nd station back