### success (admin)
DELETE {{baseUrl}}/api/admin/city/376
Authorization: admin:admin

### success (admin)
DELETE {{baseUrl}}/api/admin/city?name=八原
Authorization: admin:admin

### fail: no such city
DELETE {{baseUrl}}/api/admin/city?name=NullName
Authorization: admin:admin

###
