### success (admin)
DELETE {{baseUrl}}/api/admin/train/12000T999000
Authorization: admin:admin

### fail: param error
DELETE {{baseUrl}}/api/admin/train/12000T999000XX
Authorization: admin:admin

###
