spring:
  profiles:
#    active: @profileActive@
#    active: cloud
    active: prod
  mvc:
    view:
      suffix: .html
      prefix: /templates/

mybatis:
  type-aliases-package: com.dbpp.my12306.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true